# Generated by Django 4.2.9 on 2024-03-08 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.URLField(default=None, null=True)),
                ("description", models.CharField(max_length=5000)),
                (
                    "configure_at",
                    models.CharField(default=None, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "integration",
            },
        ),
        migrations.CreateModel(
            name="UserIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(max_length=250)),
                (
                    "account_display_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("meta_data", models.TextField(default=None, null=True)),
                ("configuration", models.JSONField(default=None, null=True)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_integrations",
                        to="integration.integration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Integration",
                "verbose_name_plural": "User Integration",
                "db_table": "user_integration",
                "unique_together": {("user", "integration", "account_id")},
            },
        ),
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(default=None, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_events",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Event",
                "verbose_name_plural": "Integration Event",
                "db_table": "integration_event",
                "unique_together": {("integration", "name")},
            },
        ),
        migrations.CreateModel(
            name="DisabledUserIntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actions", models.JSONField(default=list)),
                (
                    "integration_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_user_integration_events",
                        to="integration.integrationevent",
                    ),
                ),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_user_integration_events",
                        to="integration.userintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disabled User Integration Event",
                "verbose_name_plural": "Disabled User Integration Event",
                "db_table": "disabled_user_integration_event",
                "unique_together": {("user_integration", "integration_event")},
            },
        ),
    ]
