# Generated by Django 4.2 on 2023-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("integration", "0001_initial"),
        ("integration", "0002_integration_logo"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=5000)),
                ("meta_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("logo", models.URLField(default=None, null=True)),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "integration",
                "ordering": ["id"],
            },
        ),
    ]
