# Generated by Django 4.2.4 on 2023-09-29 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("integration", "0001_initial"),
        ("integration", "0002_userintegration_account_display_name"),
        ("integration", "0003_userintegration_configuration"),
        ("integration", "0004_integration_configure_at"),
        ("integration", "0005_userintegration_is_revoked"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.URLField(default=None, null=True)),
                ("description", models.CharField(max_length=5000)),
                ("meta_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configure_at",
                    models.CharField(default=None, max_length=250, null=True),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "integration",
            },
        ),
        migrations.CreateModel(
            name="UserIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(max_length=250)),
                ("meta_data", models.TextField(default=None, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_integrations",
                        to="integration.integration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account_display_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("configuration", models.JSONField(default=None, null=True)),
                ("is_revoked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User Integration",
                "verbose_name_plural": "User Integration",
                "db_table": "user_integration",
                "unique_together": {("user", "integration", "account_id")},
            },
        ),
    ]
