# Generated by Django 4.2.9 on 2024-04-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="to_be_shown",
            field=models.BooleanField(default=True),
        ),
    ]
