# Generated by Django 4.2 on 2023-08-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegration",
            name="account_display_name",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
