# Generated by Django 4.2 on 2023-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0002_integrationuser_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationuser",
            name="tag",
        ),
        migrations.AddField(
            model_name="integration",
            name="tag",
            field=models.CharField(default="inbox", max_length=100),
            preserve_default=False,
        ),
    ]
