# Generated by Django 4.2 on 2023-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0002_remove_integration_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userintegration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
