# Generated by Django 4.2 on 2023-08-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_remove_integrationuser_tag_integration_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationuser",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_users",
                to="integration.integration",
            ),
        ),
    ]
