# Generated by Django 4.2 on 2023-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_integrationuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationuser",
            name="account_id",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="integrationuser",
            unique_together={("user_id", "integration_id", "account_id")},
        ),
    ]
