# Generated by Django 4.2 on 2023-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_userintegration_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="configure_at",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
