# Generated by Django 4.2.4 on 2023-08-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0004_integration_configure_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegration",
            name="is_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
