# Generated by Django 4.2.4 on 2023-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial_squashed_0005_userintegration_is_revoked"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegration",
            name="is_wip",
            field=models.BooleanField(default=False),
        ),
    ]
