# Generated by Django 4.2.9 on 2024-02-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("integration", "0006_userintegration_is_wip"),
        ("integration", "0007_remove_userintegration_is_wip_integration_is_wip"),
        ("integration", "0008_integrationevent_disableduserintegrationevent"),
        ("integration", "0009_integrationevent_meta_data"),
        ("integration", "0010_rename_meta_data_integrationevent_description"),
        ("integration", "0011_rename_event_type_integrationevent_name_and_more"),
        ("integration", "0012_integrationevent_actions"),
        ("integration", "0013_remove_integrationevent_actions_and_more"),
        ("integration", "0014_alter_disableduserintegrationevent_actions"),
    ]

    dependencies = [
        ("integration", "0001_initial_squashed_0005_userintegration_is_revoked"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="is_wip",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_events",
                        to="integration.integration",
                    ),
                ),
                ("description", models.TextField(default=None, null=True)),
            ],
            options={
                "verbose_name": "Integration Event",
                "verbose_name_plural": "Integration Event",
                "db_table": "integration_event",
                "unique_together": {("integration", "name")},
            },
        ),
        migrations.CreateModel(
            name="DisabledUserIntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_user_integration_events",
                        to="integration.integrationevent",
                    ),
                ),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_user_integration_events",
                        to="integration.userintegration",
                    ),
                ),
                ("actions", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Disabled User Integration Event",
                "verbose_name_plural": "Disabled User Integration Event",
                "db_table": "disabled_user_integration_event",
                "unique_together": {("user_integration", "integration_event")},
            },
        ),
    ]
