# Generated by Django 4.2.4 on 2023-11-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0006_userintegration_is_wip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userintegration",
            name="is_wip",
        ),
        migrations.AddField(
            model_name="integration",
            name="is_wip",
            field=models.BooleanField(default=False),
        ),
    ]
