# Generated by Django 4.2.4 on 2024-01-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0007_remove_userintegration_is_wip_integration_is_wip"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=250)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_events",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Event",
                "verbose_name_plural": "Integration Event",
                "db_table": "integration_event",
                "unique_together": {("integration", "event_type")},
            },
        ),
        migrations.CreateModel(
            name="DisabledUserIntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_user_integration_events",
                        to="integration.integrationevent",
                    ),
                ),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_user_integration_events",
                        to="integration.userintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disabled User Integration Event",
                "verbose_name_plural": "Disabled User Integration Event",
                "db_table": "disabled_user_integration_event",
                "unique_together": {("user_integration", "integration_event")},
            },
        ),
    ]
