# Generated by Django 4.2.4 on 2024-01-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0008_integrationevent_disableduserintegrationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationevent",
            name="meta_data",
            field=models.TextField(default=None, null=True),
        ),
    ]
