# Generated by Django 4.2.4 on 2024-01-05 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0009_integrationevent_meta_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integrationevent",
            old_name="meta_data",
            new_name="description",
        ),
    ]
