# Generated by Django 4.2.4 on 2024-01-06 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0010_rename_meta_data_integrationevent_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integrationevent",
            old_name="event_type",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="integrationevent",
            unique_together={("integration", "name")},
        ),
    ]
