# Generated by Django 4.2.9 on 2024-01-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0011_rename_event_type_integrationevent_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationevent",
            name="actions",
            field=models.JSONField(default=[]),
        ),
    ]
