# Generated by Django 4.2.9 on 2024-01-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0012_integrationevent_actions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationevent",
            name="actions",
        ),
        migrations.AddField(
            model_name="disableduserintegrationevent",
            name="actions",
            field=models.JSONField(default=[]),
        ),
    ]
