# Generated by Django 4.2.9 on 2024-01-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0013_remove_integrationevent_actions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disableduserintegrationevent",
            name="actions",
            field=models.JSONField(default=list),
        ),
    ]
