# Generated by Django 4.2.9 on 2024-02-28 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "integration",
            "0006_userintegration_is_wip_squashed_0014_alter_disableduserintegrationevent_actions",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="is_wip",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="meta_data",
        ),
        migrations.RemoveField(
            model_name="integrationevent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="integrationevent",
            name="updated_at",
        ),
    ]
