# Generated by Django 4.2.4 on 2023-09-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("inbox", "0001_initial"),
        ("inbox", "0002_inboxitem_category"),
        ("inbox", "0003_alter_inboxitem_cause"),
        ("inbox", "0004_remove_outlookmail_user_integration_and_more"),
        ("inbox", "0005_rename_inboxitem_inbox_alter_inbox_options_and_more"),
        ("inbox", "0006_alter_inbox_options"),
    ]

    dependencies = [
        ("integration", "0005_userintegration_is_revoked"),
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.CharField(db_index=True, max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(default=None, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("cause", models.CharField(default=None, max_length=10000, null=True)),
                ("is_body_html", models.BooleanField(default=False)),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_items",
                        to="integration.userintegration",
                    ),
                ),
                ("category", models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Inbox",
                "verbose_name_plural": "Inbox",
                "db_table": "inbox_item",
            },
        ),
        migrations.AlterModelTable(
            name="inbox",
            table="inbox",
        ),
        migrations.AlterModelOptions(
            name="inbox",
            options={"verbose_name": "Inbox"},
        ),
    ]
