# Generated by Django 4.2 on 2023-08-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0004_alter_integrationuser_integration"),
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlemail",
            name="integration_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_mails",
                to="integration.integrationuser",
            ),
            preserve_default=False,
        ),
    ]
