# Generated by Django 4.2 on 2023-08-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlemail",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="googlemail",
            name="message_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
