# Generated by Django 4.2 on 2023-08-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0002_remove_integration_tag"),
        ("inbox", "0002_googlemail_is_read_alter_googlemail_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(default=None, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_items",
                        to="integration.userintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbox Item",
                "verbose_name_plural": "Inbox Items",
                "db_table": "inbox_item",
            },
        ),
        migrations.DeleteModel(
            name="UserInbox",
        ),
    ]
