# Generated by Django 4.2 on 2023-08-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0002_googlemail_integration_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googlemail",
            old_name="data",
            new_name="payload",
        ),
        migrations.AddField(
            model_name="googlemail",
            name="internal_date",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="googlemail",
            name="label_ids",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="googlemail",
            name="size_estimate",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="googlemail",
            name="snippet",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
