# Generated by Django 4.2.4 on 2023-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0002_inboxitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxitem",
            name="cause",
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
