# Generated by Django 4.2 on 2023-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0003_rename_data_googlemail_payload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlemail",
            name="message_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
