# Generated by Django 4.2 on 2023-08-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0004_inboxitem_cause_inboxitem_is_body_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxitem",
            name="uid",
            field=models.CharField(
                db_index=True, default=1, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
