# Generated by Django 4.2 on 2023-08-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_alter_integration_id_alter_userintegration_id"),
        ("inbox", "0006_remove_googlemail_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlemail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inboxitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="OutlookMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("categories", models.JSONField()),
                ("payload", models.JSONField()),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlook_mails",
                        to="integration.userintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outlook Mail",
                "verbose_name_plural": "Outlook Mails",
                "db_table": "outlook_mail",
            },
        ),
    ]
