# Generated by Django 4.2.4 on 2023-10-03 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0001_initial_squashed_0006_alter_inbox_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="is_deleted",
        ),
    ]
