# Generated by Django 4.2.9 on 2024-02-28 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("inbox", "0007_remove_inbox_is_deleted"),
        ("inbox", "0008_inbox_i_am_mentioned"),
        ("inbox", "0009_inbox_attachments"),
        ("inbox", "0010_alter_inbox_uid_alter_inbox_unique_together"),
        ("inbox", "0011_inbox_is_read"),
        ("inbox", "0012_blockedemail"),
        ("inbox", "0013_alter_blockedemail_unique_together_blockedemail_user_and_more"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0001_initial_squashed_0006_alter_inbox_options"),
        ("integration", "0014_alter_disableduserintegrationevent_actions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="inbox",
            name="i_am_mentioned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inbox",
            name="attachments",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="inbox",
            name="uid",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="inbox",
            unique_together={("uid", "user_integration")},
        ),
        migrations.AddField(
            model_name="inbox",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Email",
                "db_table": "blocked_email",
                "unique_together": {("email", "user")},
            },
        ),
    ]
