# Generated by Django 4.2.9 on 2024-01-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0007_remove_inbox_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="i_am_mentioned",
            field=models.BooleanField(default=False),
        ),
    ]
