# Generated by Django 4.2.9 on 2024-02-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0008_inbox_i_am_mentioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="attachments",
            field=models.JSONField(default=None, null=True),
        ),
    ]
