# Generated by Django 4.2.9 on 2024-02-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_disableduserintegrationevent_actions"),
        ("inbox", "0011_inbox_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(max_length=255)),
                (
                    "user_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_emails",
                        to="integration.userintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Email",
                "db_table": "blocked_email",
                "unique_together": {("email", "user_integration")},
            },
        ),
    ]
