# Generated by Django 4.2.9 on 2024-02-28 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "inbox",
            "0007_remove_inbox_is_deleted_squashed_0013_alter_blockedemail_unique_together_blockedemail_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedemail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
