# Generated by Django 4.2.9 on 2024-03-01 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0014_alter_blockedemail_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockedEmail",
        ),
    ]
