# Generated by Django 4.2.9 on 2024-03-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0015_delete_blockedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="snoozed_till",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="inbox",
            name="status",
            field=models.IntegerField(
                choices=[
                    (-2, "Pending"),
                    (-1, "Rejected"),
                    (0, "Snoozed"),
                    (1, "Accepted"),
                    (2, "Duplicate"),
                ],
                default=-2,
            ),
        ),
    ]
