# Generated by Django 4.2.9 on 2024-03-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
        ("inbox", "0016_inbox_snoozed_till_inbox_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="issue",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_inbox",
                to="project.issue",
            ),
        ),
    ]
