# Generated by Django 4.2.10 on 2024-04-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_subscription_limits"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=1000, unique=True)),
            ],
            options={
                "verbose_name": "Subscription Webhook Event",
                "verbose_name_plural": "Subscription Webhook Events",
                "db_table": "subscription_webhook_event",
            },
        ),
    ]
