# Generated by Django 4.2.10 on 2024-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_subscriptionwebhookevent_event_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="valid_till",
        ),
    ]
