# Generated by Django 4.2.11 on 2024-05-22 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial_squashed_0005_remove_subscription_valid_till"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionwebhookevent",
            name="event_body",
        ),
    ]
