# Generated by Django 4.2.11 on 2024-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_subscription_customer_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_details",
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_id",
            field=models.CharField(default=None, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
