# Generated by Django 4.2.4 on 2023-09-29 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("client", "0001_initial"),
        ("client", "0002_remove_client_tax_number_client_tax_code_and_more"),
        ("client", "0003_remove_client_city_remove_client_country_and_more"),
        ("client", "0004_alter_client_unique_together"),
        ("client", "0005_avatar"),
        ("client", "0006_remove_client_logo_client_avatar"),
        ("client", "0007_alter_client_website"),
        ("client", "0008_alter_client_options_remove_avatar_name_and_more"),
        ("client", "0009_alter_client_address_alter_client_email_and_more"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="Avatars")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avatar",
                "verbose_name_plural": "Avatars",
                "db_table": "avatar",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("notes", models.TextField(null=True)),
                ("website", models.CharField(max_length=255, null=True)),
                ("file_ids", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_avatar",
                        to="client.avatar",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "name")},
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelTable(
            name="client",
            table="client",
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
