# Generated by Django 4.2.4 on 2023-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="tax_number",
        ),
        migrations.AddField(
            model_name="client",
            name="tax_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="tax_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="currency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="description",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="zip_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
