# Generated by Django 4.2.4 on 2023-09-27 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_remove_client_tax_number_client_tax_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
        migrations.RemoveField(
            model_name="client",
            name="country",
        ),
        migrations.RemoveField(
            model_name="client",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="client",
            name="description",
        ),
        migrations.RemoveField(
            model_name="client",
            name="state",
        ),
        migrations.RemoveField(
            model_name="client",
            name="tax_code",
        ),
        migrations.RemoveField(
            model_name="client",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="client",
            name="zip_code",
        ),
    ]
