# Generated by Django 4.2.4 on 2023-09-27 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0003_remove_client_city_remove_client_country_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("user", "name")},
        ),
    ]
