# Generated by Django 4.2.4 on 2023-09-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="logo",
        ),
        migrations.AddField(
            model_name="client",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_avatar",
                to="client.avatar",
            ),
        ),
    ]
