# Generated by Django 4.2.4 on 2023-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_remove_client_logo_client_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="website",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
