# Generated by Django 4.2.4 on 2023-09-27 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_alter_client_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="name",
        ),
        migrations.AlterModelTable(
            name="client",
            table="client",
        ),
    ]
