# Generated by Django 4.2.4 on 2023-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_alter_client_options_remove_avatar_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
