# Generated by Django 4.2.9 on 2024-02-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0001_initial_squashed_0009_alter_client_address_alter_client_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="notes",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="website",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
