# Generated by Django 4.2.9 on 2024-02-28 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0014_delete_project"),
        ("client", "0010_alter_client_address_alter_client_email_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="client",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="client",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
        migrations.DeleteModel(
            name="Avatar",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
