repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort . --check --diff
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black . --check
        language: system
        types: [python]
        pass_filenames: false
