repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black . --check --diff
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.1
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
