# Generated by Django 4.2.9 on 2024-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(default=None, null=True, upload_to="Documents"),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.CharField(default=None, max_length=5000, null=True)),
                ("uid", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "document",
            },
        ),
    ]
