# Generated by Django 4.2.4 on 2023-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="link",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="Documents"),
        ),
    ]
