# Generated by Django 4.2.9 on 2024-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="document",
            name="user_integration",
        ),
        migrations.AddField(
            model_name="document",
            name="meta_data",
            field=models.JSONField(default=dict),
        ),
    ]
