# Generated by Django 4.2.4 on 2023-11-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0007_remove_userintegration_is_wip_integration_is_wip"),
        ("document", "0002_document_link_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="user_integration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integration.userintegration",
            ),
        ),
    ]
