# Generated by Django 4.2.9 on 2024-03-03 07:26

import django.db.models.deletion
from django.db import migrations, models

import common.file_field


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0002_team_teammember_workspace_alter_user_options_and_more"),
        (
            "document",
            "0003_remove_document_uid_remove_document_user_integration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="workspace",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="iam.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                default=None,
                null=True,
                upload_to=common.file_field.upload_path,
                validators=[common.file_field.file_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="link",
            field=models.URLField(default=None, null=True),
        ),
    ]
