# Generated by Django 4.2.9 on 2024-02-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0008_inbox_i_am_mentioned"),
        ("document", "0003_document_user_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="inbox_item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="inbox.inbox"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="link",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
