# Generated by Django 4.2.9 on 2024-02-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
        ("document", "0004_document_inbox_item_alter_document_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(to="tag.tag"),
        ),
    ]
