# Generated by Django 4.2.9 on 2024-03-08 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0005_document_created_by_document_updated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="user",
        ),
    ]
