# Generated by Django 4.2.9 on 2024-02-13 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0005_document_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="inbox_item",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tags",
        ),
    ]
