# Generated by Django 4.2.9 on 2024-02-13 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_disableduserintegrationevent_actions"),
        ("document", "0006_remove_document_inbox_item_remove_document_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="inbox_uid",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="Documents"),
        ),
        migrations.AlterField(
            model_name="document",
            name="link",
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="user_integration",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integration.userintegration",
            ),
        ),
    ]
