# Generated by Django 4.2.9 on 2024-02-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0007_document_inbox_uid_alter_document_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="inbox_uid",
        ),
        migrations.AddField(
            model_name="document",
            name="uid",
            field=models.CharField(
                db_index=True, default=1, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
