# Generated by Django 4.2.9 on 2024-03-02 05:15

import django.db.models.deletion
from django.db import migrations, models

import common.utils.file_field


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0002_workspace_workspaceinvite_workspacemember_and_more"),
        ("document", "0008_remove_document_inbox_uid_document_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="document",
            name="user_integration",
        ),
        migrations.AddField(
            model_name="document",
            name="attributes",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="document",
            name="workspace",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="iam.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                default=None,
                null=True,
                upload_to=common.utils.file_field.upload_path,
                validators=[common.utils.file_field.file_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="link",
            field=models.URLField(default=None, null=True),
        ),
    ]
