# Generated by Django 4.2.9 on 2024-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemember",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Admin"), (1, "Member"), (0, "Guest")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="workspacememberinvite",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Admin"), (1, "Member"), (0, "Guest")], default=1
            ),
        ),
    ]
