# Generated by Django 4.2.9 on 2024-03-02 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0002_workspace_workspaceinvite_workspacemember_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="workspaceuserproperties",
            table="workspace_user_property",
        ),
    ]
