# Generated by Django 4.2.9 on 2024-03-02 06:25

from django.db import migrations, models

import common.utils.file_field


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0003_alter_workspaceuserproperties_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.FileField(
                default=None,
                null=True,
                upload_to=common.utils.file_field.upload_path,
                validators=[common.utils.file_field.file_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.FileField(
                default=None,
                null=True,
                upload_to=common.utils.file_field.upload_path,
                validators=[common.utils.file_field.file_size_validator],
            ),
        ),
    ]
