# Generated by Django 4.2.9 on 2024-03-05 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0003_usernotificationpreference_project_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNotificationPreference",
        ),
    ]
