# Generated by Django 4.2.9 on 2024-03-08 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0004_delete_usernotificationpreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspacemember",
            name="invite",
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_workspace",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_member",
                to="iam.workspace",
            ),
        ),
    ]
