# Generated by Django 4.2.9 on 2024-03-13 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0004_alter_teammember_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkspaceTheme",
        ),
    ]
