# Generated by Django 4.2.9 on 2024-03-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0004_alter_user_profile_image_alter_workspace_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="WorkspaceMemberInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(null=True)),
                ("token", models.CharField(max_length=255)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (3, "Owner"),
                            (2, "Admin"),
                            (1, "Member"),
                            (0, "Guest"),
                        ],
                        default=10,
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.workspace"
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Member Invite",
                "verbose_name_plural": "Workspace Member Invites",
                "db_table": "workspace_member_invite",
            },
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="invite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="iam.workspacememberinvite",
            ),
        ),
        migrations.DeleteModel(
            name="WorkspaceInvite",
        ),
    ]
