# Generated by Django 4.2.9 on 2024-03-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0004_delete_usernotificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
