# Generated by Django 4.2.9 on 2024-03-13 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0005_delete_workspacetheme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkspaceUserProperties",
        ),
    ]
