# Generated by Django 4.2.9 on 2024-03-08 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0005_remove_workspacemember_invite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_workspace_id",
        ),
    ]
