# Generated by Django 4.2.9 on 2024-03-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0006_delete_workspaceuserproperties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.URLField(default=None, null=True),
        ),
    ]
