# Generated by Django 4.2.9 on 2024-03-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0006_remove_user_last_workspace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_workspace_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
