# Generated by Django 4.2.9 on 2024-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0008_alter_workspacemember_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input", models.CharField(max_length=255)),
                ("otp", models.CharField(max_length=8)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Login OTP",
                "verbose_name_plural": "Login OTPs",
                "db_table": "login_otp",
            },
        ),
    ]
