# Generated by Django 4.2.9 on 2024-04-03 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0009_loginotp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginotp",
            name="is_verified",
        ),
    ]
