# Generated by Django 4.2.11 on 2024-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0011_workspacemember_auto_approve_tracked_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="utm_campaign",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="utm_medium",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="utm_source",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
