# Generated by Django 4.2.9 on 2024-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analytic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("query", models.JSONField()),
                ("query_dict", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Analytic",
                "verbose_name_plural": "Analytics",
                "db_table": "analytic",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description_html", models.TextField(blank=True, default="<p></p>")),
                ("identifier", models.BigIntegerField(null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "type_identifier",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("project", "Project"),
                            ("home", "Home"),
                            ("user", "User"),
                        ],
                        default="home",
                        max_length=30,
                        verbose_name="Dashboard Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "db_table": "dashboard",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("filters", models.JSONField(default=dict)),
                ("properties", models.JSONField(default=dict)),
                ("sort_order", models.FloatField(default=65535)),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "db_table": "dashboard_widget",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255)),
                ("filters", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgets",
                "db_table": "widget",
                "ordering": ("-created_at",),
            },
        ),
    ]
