# Generated by Django 4.2.9 on 2024-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="sort_order",
            field=models.FloatField(default=65535),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="type_identifier",
            field=models.CharField(
                choices=[
                    ("workspace", "Workspace"),
                    ("project", "Project"),
                    ("home", "Home"),
                    ("user", "User"),
                ],
                default="home",
                max_length=30,
                verbose_name="Dashboard Type",
            ),
        ),
    ]
