# Generated by Django 4.2.9 on 2024-03-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0002_team_teammember_workspace_alter_user_options_and_more"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytic",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="iam.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardwidget",
            unique_together={("widget", "dashboard")},
        ),
    ]
