# Generated by Django 4.2.9 on 2024-03-15 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="updated_by",
        ),
    ]
