# Generated by Django 4.2.9 on 2024-03-17 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_widget_created_by_remove_widget_updated_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analytic",
        ),
    ]
