INSERT INTO integration_event (id, "name", integration_id, description) VALUES(1, 'FILE_UPDATE', 5, 'File was updated');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(2, 'FILE_DELETE', 5, 'File was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(3, 'FILE_VERSION_UPDATE', 5, 'File version was updated');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(4, 'FILE_COMMENT', 5, 'File was commented on');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(5, 'LIBRARY_PUBLISH', 5, 'Library was published');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(6, 'app_home_opened', 4, 'User clicked into your App Home');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(7, 'app_mention', 4, 'Subscribe to only the message events that mention your app or bot');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(8, 'app_rate_limited', 4, 'Indicates your app''s event subscriptions are being rate limited');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(9, 'app_requested', 4, 'User requested an app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(10, 'app_uninstalled', 4, 'Your Slack app was uninstalled.');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(11, 'call_rejected', 4, 'A Call was rejected');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(12, 'channel_archive', 4, 'A channel was archived');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(13, 'channel_created', 4, 'A channel was created');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(14, 'channel_deleted', 4, 'A channel was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(15, 'channel_history_changed', 4, 'Bulk updates were made to a channel''s history');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(16, 'channel_id_changed', 4, 'A channel ID changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(17, 'channel_left', 4, 'You left a channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(18, 'channel_rename', 4, 'A channel was renamed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(19, 'channel_shared', 4, 'A channel has been shared with an external workspace');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(20, 'channel_unarchive', 4, 'A channel was unarchived');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(21, 'channel_unshared', 4, 'A channel has been unshared with an external workspace');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(22, 'dnd_updated', 4, 'Do not Disturb settings changed for the current user');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(23, 'dnd_updated_user', 4, 'Do not Disturb settings changed for a member');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(24, 'email_domain_changed', 4, 'The workspace email domain has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(25, 'emoji_changed', 4, 'A custom emoji has been added or changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(26, 'file_change', 4, 'A file was changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(27, 'file_comment_added', 4, 'A file comment was added');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(28, 'file_comment_deleted', 4, 'A file comment was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(29, 'file_comment_edited', 4, 'A file comment was edited');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(30, 'file_created', 4, 'A file was created');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(31, 'file_deleted', 4, 'A file was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(32, 'file_public', 4, 'A file was made public');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(33, 'file_shared', 4, 'A file was shared');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(34, 'file_unshared', 4, 'A file was unshared');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(35, 'grid_migration_finished', 4, 'An enterprise grid migration has finished on this workspace.');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(36, 'grid_migration_started', 4, 'An enterprise grid migration has started on this workspace.');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(37, 'group_archive', 4, 'A private channel was archived');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(38, 'group_close', 4, 'You closed a private channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(39, 'group_deleted', 4, 'A private channel was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(40, 'group_history_changed', 4, 'Bulk updates were made to a private channel''s history');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(41, 'group_left', 4, 'You left a private channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(42, 'group_open', 4, 'You created a group DM');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(43, 'group_rename', 4, 'A private channel was renamed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(44, 'group_unarchive', 4, 'A private channel was unarchived');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(45, 'im_close', 4, 'You closed a DM');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(46, 'im_created', 4, 'A DM was created');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(47, 'im_history_changed', 4, 'Bulk updates were made to a DM''s history');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(48, 'im_open', 4, 'You opened a DM');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(49, 'invite_requested', 4, 'User requested an invite');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(50, 'link_shared', 4, 'A message was posted containing one or more links relevant to your application');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(51, 'member_joined_channel', 4, 'A user joined a public channel, private channel or MPDM.');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(52, 'member_left_channel', 4, 'A user left a public or private channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(53, 'message', 4, 'A message was sent to a channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(54, 'message.app_home', 4, 'A user sent a message to your Slack app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(55, 'message.channels', 4, 'A message was posted to a channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(56, 'message.groups', 4, 'A message was posted to a private channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(57, 'message.im', 4, 'A message was posted in a direct message channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(58, 'message.mpim', 4, 'A message was posted in a multiparty direct message channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(59, 'message_metadata_deleted', 4, 'Message metadata was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(60, 'message_metadata_posted', 4, 'Message metadata was posted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(61, 'message_metadata_updated', 4, 'Message metadata was updated');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(62, 'pin_added', 4, 'A pin was added to a channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(63, 'pin_removed', 4, 'A pin was removed from a channel');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(64, 'reaction_added', 4, 'A member has added an emoji reaction to an item');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(65, 'reaction_removed', 4, 'A member removed an emoji reaction');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(66, 'scope_denied', 4, 'OAuth scopes were denied to your app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(67, 'scope_granted', 4, 'OAuth scopes were granted to your app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(68, 'shared_channel_invite_accepted', 4, 'A shared channel invite was accepted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(69, 'shared_channel_invite_approved', 4, 'A shared channel invite was approved');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(70, 'shared_channel_invite_declined', 4, 'A shared channel invite was declined');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(71, 'shared_channel_invite_received', 4, 'A shared channel invite was sent to a Slack user');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(72, 'star_added', 4, 'A member has saved an item for later or starred an item');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(73, 'star_removed', 4, 'A member has removed an item saved for later or starred an item');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(74, 'subteam_created', 4, 'A User Group has been added to the workspace');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(75, 'subteam_members_changed', 4, 'The membership of an existing User Group has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(76, 'subteam_self_added', 4, 'You have been added to a User Group');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(77, 'subteam_self_removed', 4, 'You have been removed from a User Group');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(78, 'subteam_updated', 4, 'An existing User Group has been updated or its members changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(79, 'team_access_granted', 4, 'Access to a set of teams was granted to your org app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(80, 'issues', 6, 'An event related to an issue');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(81, 'team_access_revoked', 4, 'Access to a set of teams was revoked from your org app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(82, 'team_domain_change', 4, 'The workspace domain has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(83, 'team_join', 4, 'A new member has joined');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(84, 'team_rename', 4, 'The workspace name has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(85, 'tokens_revoked', 4, 'API tokens for your app were revoked.');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(86, 'url_verification', 4, 'Verifies ownership of an  Request URL');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(87, 'user_change', 4, 'A member''s data has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(88, 'user_huddle_changed', 4, 'A user''s huddle status has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(89, 'user_profile_changed', 4, 'A user''s profile data has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(90, 'user_resource_denied', 4, 'User resource was denied to your app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(91, 'user_resource_granted', 4, 'User resource was granted to your app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(92, 'user_resource_removed', 4, 'User resource was removed from your app');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(93, 'user_status_changed', 4, 'A user''s status has changed');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(94, 'workflow_deleted', 4, 'A workflow that contains a step supported by your app was deleted');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(95, 'workflow_published', 4, 'A workflow that contains a step supported by your app was published');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(96, 'workflow_step_deleted', 4, 'A workflow step supported by your app was removed from a workflow');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(97, 'workflow_step_execute', 4, 'A workflow step supported by your app should execute');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(98, 'workflow_unpublished', 4, 'A workflow that contains a step supported by your app was unpublished');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(100, 'pull_request', 6, 'An event related to a pull request');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(101, 'pull_request_review_thread', 6, 'An event related to a pull request review thread');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(102, 'pull_request_review_comment', 6, 'An event related to a pull request review comment');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(103, 'pull_request_review', 6, 'An event related to a pull request review');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(105, 'issue_comment', 6, 'An event related to an issue comment');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(107, 'createBoard', 8, 'Created a board');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(108, 'updateBoard', 8, 'Updated board details');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(109, 'convertToCardFromCheckItem', 8, 'Converted a check item to a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(110, 'createCard', 8, 'Created a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(111, 'deleteCard', 8, 'Deleted a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(112, 'updateCard', 8, 'Updated card details');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(113, 'removeChecklistFromCard', 8, 'Removed a checklist from a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(114, 'updateCheckItemStateOnCard', 8, 'Updated check item state on a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(115, 'updateChecklist', 8, 'Updated checklist details');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(116, 'updateList', 8, 'Updated list details');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(117, 'addLabelToCard', 8, 'A label was added to a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(118, 'createCheckItem', 8, 'Created a check item');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(119, 'deleteCheckItem', 8, 'Deleted a check item');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(120, 'removeLabelFromCard', 8, 'Removed a label from a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(121, 'updateCheckItem', 8, 'Updated check item details');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(122, 'addChecklistToCard', 8, 'A checklist was added to a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(123, 'addMemberToCard', 8, 'A member was added to a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(124, 'addMemberToBoard', 8, 'A member was added to a board');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(125, 'moveCardFromBoard', 8, 'Moved a card from one board to another');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(126, 'moveCardToBoard', 8, 'Moved a card to a different board');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(127, 'moveListFromBoard', 8, 'Moved a list from one board to another');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(128, 'moveListToBoard', 8, 'Moved a list to a different board');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(129, 'deleteComment', 8, 'Someone deleted their comment on a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(130, 'updateComment', 8, 'Someone updated their comment on a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(131, 'commentCard', 8, 'Someone commented on a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(132, 'deleteAttachmentFromCard', 8, 'Deleted an attachment from a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(133, 'addAttachmentToCard', 8, 'An attachment was added to a card');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(137, 'jira:issue_created', 9, 'An issue was created on Jira');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(138, 'jira:issue_updated', 9, 'An issue was updated on Jira');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(136, 'story', 7, 'An event related to a story');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(139, 'jira:issue_deleted', 9, 'An issue was deleted on Jira');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(140, 'comment_created', 9, 'A comment was added on Jira');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(141, 'comment_updated', 9, 'A comment was updated on Jira');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(142, 'comment_deleted', 9, 'A comment was deleted on Jira');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(134, 'project', 7, 'An event related to a project');
INSERT INTO integration_event (id, "name", integration_id, description) VALUES(135, 'task', 7, 'An event related to a task');