# Generated by Django 4.2.4 on 2023-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="uid",
            field=models.CharField(
                db_index=True, default=1, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
