# Generated by Django 4.2.4 on 2023-10-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_task_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="uid",
            field=models.CharField(max_length=100),
        ),
    ]
