# Generated by Django 4.2.4 on 2023-10-18 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_alter_task_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
    ]
