# Generated by Django 4.2.9 on 2024-03-02 06:25

import django.contrib.postgres.fields
from django.db import migrations, models

import common.file_field


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueactivity",
            name="attachments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FileField(
                    upload_to=common.file_field.upload_path,
                    validators=[common.file_field.file_size_validator],
                ),
                blank=True,
                default=list,
                size=10,
            ),
        ),
        migrations.AlterField(
            model_name="issuecomment",
            name="attachments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FileField(
                    upload_to=common.file_field.upload_path,
                    validators=[common.file_field.file_size_validator],
                ),
                blank=True,
                default=list,
                size=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.FileField(
                default=None,
                null=True,
                upload_to=common.file_field.upload_path,
                validators=[common.file_field.file_size_validator],
            ),
        ),
    ]
