# Generated by Django 4.2.9 on 2024-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_projectmember_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.URLField(default=None, null=True),
        ),
    ]
