# Generated by Django 4.2.9 on 2024-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
