# Generated by Django 4.2.4 on 2023-09-27 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_project_file_ids"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectFile",
        ),
    ]
