# Generated by Django 4.2.9 on 2024-03-18 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_issueview_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issueattachment",
            old_name="asset",
            new_name="file",
        ),
    ]
