# Generated by Django 4.2.4 on 2023-10-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0001_initial_squashed_0009_alter_client_address_alter_client_email_and_more",
        ),
        ("project", "0001_initial_squashed_0005_delete_projectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
            ),
        ),
    ]
