# Generated by Django 4.2.9 on 2024-03-20 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_rename_asset_issueattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="estimate_point",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
