# Generated by Django 4.2.9 on 2024-03-20 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_alter_issue_estimate_point"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectMemberInvite",
        ),
    ]
