# Generated by Django 4.2.4 on 2023-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_alter_project_user_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meta_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="uid",
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
