# Generated by Django 4.2.4 on 2023-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_project_meta_data_project_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uid",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
