# Generated by Django 4.2.10 on 2024-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_projecttemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttemplate",
            name="states",
        ),
        migrations.AlterField(
            model_name="projecttemplate",
            name="estimates",
            field=models.JSONField(
                default={
                    "description": "An estimate model using Fibonacci sequence for measuring development effort.",
                    "name": "Effort Estimate",
                    "points": [
                        {"description": "", "estimate": 4, "key": 0, "value": "1"},
                        {"description": "", "estimate": 4, "key": 5, "value": "13"},
                        {"description": "", "estimate": 4, "key": 1, "value": "2"},
                        {"description": "", "estimate": 4, "key": 2, "value": "3"},
                        {"description": "", "estimate": 4, "key": 3, "value": "5"},
                        {"description": "", "estimate": 4, "key": 4, "value": "8"},
                    ],
                }
            ),
        ),
        migrations.AlterField(
            model_name="projecttemplate",
            name="labels",
            field=models.JSONField(
                default=[
                    {"color": "#d73a4a", "name": "Bug", "sort_order": 65535},
                    {
                        "color": "#a2eeef",
                        "name": "Feature Request",
                        "sort_order": 75535,
                    },
                    {"color": "#84b6eb", "name": "Enhancement", "sort_order": 85535},
                    {"color": "#bfdadc", "name": "Documentation", "sort_order": 95535},
                    {"color": "#f9c513", "name": "Design", "sort_order": 105535},
                    {"color": "#5752d9", "name": "Performance", "sort_order": 115535},
                    {"color": "#e99695", "name": "Security", "sort_order": 125535},
                    {"color": "#f9d0c4", "name": "Testing", "sort_order": 135535},
                    {"color": "#fad8c7", "name": "Refactor", "sort_order": 145535},
                    {"color": "#e12d2d", "name": "Critical", "sort_order": 155535},
                    {"color": "#ffffff", "name": "Wontfix", "sort_order": 165535},
                    {"color": "#cc317c", "name": "Question", "sort_order": 175535},
                    {"color": "#128A0C", "name": "Help Wanted", "sort_order": 185535},
                    {
                        "color": "#7057ff",
                        "name": "Good First Issue",
                        "sort_order": 195535,
                    },
                    {"color": "#d4c5f9", "name": "Backend", "sort_order": 205535},
                    {"color": "#bfd4f2", "name": "Frontend", "sort_order": 215535},
                    {"color": "#b2b7ff", "name": "API", "sort_order": 225535},
                    {"color": "#1d76db", "name": "DevOps", "sort_order": 235535},
                ]
            ),
        ),
    ]
