# Generated by Django 4.2.4 on 2023-10-18 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0011_alter_project_uid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("user", "uid")},
        ),
    ]
