# Generated by Django 4.2.10 on 2024-04-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0010_remove_loginotp_is_verified"),
        ("project", "0011_alter_projecttemplate_estimates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttemplate",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_default_props",
                to="iam.workspace",
            ),
        ),
    ]
