# Generated by Django 4.2.4 on 2023-10-18 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_alter_project_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
    ]
