# Generated by Django 4.2.10 on 2024-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_alter_projecttemplate_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycle",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
    ]
