# Generated by Django 4.2.9 on 2024-02-28 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0013_alter_project_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
