# Generated by Django 4.2.10 on 2024-04-18 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.file_field


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iam", "0010_remove_loginotp_is_verified"),
        ("project", "0014_trackedtime_budget_projectmemberrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedTimeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_data", models.JSONField(default=dict)),
                (
                    "file",
                    models.FileField(
                        upload_to=common.file_field.upload_path,
                        validators=[common.file_field.file_size_validator],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="project.project",
                    ),
                ),
                (
                    "tracked_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="project.trackedtime",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="iam.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracked Time Attachment",
                "verbose_name_plural": "Tracked Time Attachments",
                "db_table": "tracked_time_attachment",
                "ordering": ("-created_at",),
            },
        ),
    ]
