# Generated by Django 4.2.10 on 2024-04-19 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0016_issuegitpr_issuegitcommit"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="issuegitcommit",
            unique_together={("issue", "commit_id")},
        ),
        migrations.AlterUniqueTogether(
            name="issuegitpr",
            unique_together={("issue", "pr_id")},
        ),
    ]
