# Generated by Django 4.2.10 on 2024-04-19 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_alter_issuegitcommit_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="issuegitpr",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="issuegitpr",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="issuegitpr",
            name="issue",
        ),
        migrations.RemoveField(
            model_name="issuegitpr",
            name="project",
        ),
        migrations.RemoveField(
            model_name="issuegitpr",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="issuegitpr",
            name="workspace",
        ),
        migrations.DeleteModel(
            name="IssueGitCommit",
        ),
        migrations.DeleteModel(
            name="IssueGitPR",
        ),
    ]
