# Generated by Django 4.2.10 on 2024-04-20 03:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0001_initial_squashed_0010_remove_loginotp_is_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project",
            "0001_initial_squashed_0018_alter_issuegitpr_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Budget",
            new_name="ProjectBudget",
        ),
        migrations.AlterModelOptions(
            name="projectbudget",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Project Budget",
                "verbose_name_plural": "Project Budgets",
            },
        ),
        migrations.AlterModelTable(
            name="projectbudget",
            table="project_budget",
        ),
    ]
