# Generated by Django 4.2.10 on 2024-04-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_rename_budget_projectbudget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="project.projectbudget",
            ),
        ),
    ]
