# Generated by Django 4.2.10 on 2024-04-20 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0022_alter_projectmemberrate_per_hour_or_per_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmemberrate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="projectmemberrate",
            name="project_member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_member_rate",
                to="project.projectmember",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="projectmemberrate",
            name="user",
        ),
    ]
