# Generated by Django 4.2.10 on 2024-04-22 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_trackedtime_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackedtime",
            name="cycle",
        ),
        migrations.RemoveField(
            model_name="trackedtime",
            name="module",
        ),
        migrations.RemoveField(
            model_name="trackedtime",
            name="user",
        ),
    ]
