# Generated by Django 4.2.10 on 2024-04-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0025_remove_trackedtime_cycle_remove_trackedtime_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedtime",
            name="is_manually_added",
            field=models.BooleanField(
                default=False, help_text="Is time added manually by the user"
            ),
        ),
    ]
