# Generated by Django 4.2.10 on 2024-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0026_trackedtime_is_manually_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedtime",
            name="duration",
            field=models.DurationField(
                default=None,
                help_text="Duration of the tracked time, calculated from start and end time",
                null=True,
            ),
        ),
    ]
