name: "Deploy"

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install SSH Key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy
              run: |
                  ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "cd /home/ubuntu/server && sudo git pull && /home/ubuntu/.local/bin/poetry install && /home/ubuntu/.local/bin/poetry run python manage.py migrate && sudo systemctl restart gunicorn && sudo systemctl restart nginx"
