name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH
              run: sudo apt-get install openssh-client

            - name: Copy SSH private key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Connect to EC2 instance
              run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.209.0.12 "cd /home/ubuntu/server && sudo git pull"

            - name: Install project dependencies
              run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.209.0.12 "cd /home/ubuntu/server && poetry install"

            - name: Run Django migrations
              run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.209.0.12 "cd /home/ubuntu/server && poetry run python manage.py migrate"

            - name: Restart Gunicorn
              run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.209.0.12 "sudo systemctl restart gunicorn"

            - name: Restart Nginx
              run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@44.209.0.12 "sudo systemctl restart nginx"
