name: "Deploy"

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install SSH Key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install poetry
              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  echo "export PATH=$HOME/.local/bin:$PATH" >> $HOME/.bashrc
                  source $HOME/.bashrc

            - name: Deploy
              run: |
                  ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "cd ~/server && sudo git pull && poetry install && poetry run python manage.py migrate && sudo systemctl restart gunicorn && sudo systemctl restart nginx"
